using Microsoft.EntityFrameworkCore.Migrations;

// <auto-generated />
#nullable disable
#pragma warning disable CA1861

namespace SummonersVault.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialCurrentSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "accounts",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    login_identifier = table.Column<string>(type: "TEXT", nullable: false),
                    password = table.Column<byte[]>(type: "BLOB", nullable: false),
                    label = table.Column<string>(type: "TEXT", nullable: true),
                    region = table.Column<string>(type: "TEXT", nullable: false),
                    notes = table.Column<string>(type: "TEXT", nullable: true),
                    roles = table.Column<int>(type: "INTEGER", nullable: false),
                    created_at = table.Column<string>(type: "TEXT", nullable: false),
                    modified_at = table.Column<string>(type: "TEXT", nullable: false),
                    puuid = table.Column<string>(type: "TEXT", nullable: true),
                    summoner_id = table.Column<long>(type: "INTEGER", nullable: true),
                    riot_game_name = table.Column<string>(type: "TEXT", nullable: true),
                    riot_tag_line = table.Column<string>(type: "TEXT", nullable: true),
                    profile_icon_id = table.Column<int>(type: "INTEGER", nullable: true),
                    profile_icon = table.Column<byte[]>(type: "BLOB", nullable: true),
                    summoner_level = table.Column<int>(type: "INTEGER", nullable: true),
                    last_synced_at = table.Column<string>(type: "TEXT", nullable: true),
                    last_match_played_at = table.Column<string>(type: "TEXT", nullable: true),
                    last_match_id = table.Column<long>(type: "INTEGER", nullable: true),
                    match_history_synced_at = table.Column<string>(type: "TEXT", nullable: true),
                    match_history_state = table.Column<int>(type: "INTEGER", nullable: false),
                    riot_points = table.Column<long>(type: "INTEGER", nullable: true),
                    blue_essence = table.Column<long>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_accounts", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "account_sync_categories",
                columns: table => new
                {
                    account_id = table.Column<string>(type: "TEXT", nullable: false),
                    category = table.Column<int>(type: "INTEGER", nullable: false),
                    state = table.Column<int>(type: "INTEGER", nullable: false),
                    last_attempt_at = table.Column<string>(type: "TEXT", nullable: true),
                    last_success_at = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_account_sync_categories", x => new { x.account_id, x.category });
                    table.ForeignKey(
                        name: "FK_account_sync_categories_accounts_account_id",
                        column: x => x.account_id,
                        principalTable: "accounts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "champions",
                columns: table => new
                {
                    account_id = table.Column<string>(type: "TEXT", nullable: false),
                    champion_id = table.Column<int>(type: "INTEGER", nullable: false),
                    name = table.Column<string>(type: "TEXT", nullable: false),
                    base_splash_path = table.Column<string>(type: "TEXT", nullable: true),
                    square_portrait_path = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_champions", x => new { x.account_id, x.champion_id });
                    table.ForeignKey(
                        name: "FK_champions_accounts_account_id",
                        column: x => x.account_id,
                        principalTable: "accounts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "loot_items",
                columns: table => new
                {
                    account_id = table.Column<string>(type: "TEXT", nullable: false),
                    loot_id = table.Column<string>(type: "TEXT", nullable: false),
                    loot_name = table.Column<string>(type: "TEXT", nullable: false),
                    type = table.Column<string>(type: "TEXT", nullable: false),
                    display_category = table.Column<string>(type: "TEXT", nullable: false),
                    localized_name = table.Column<string>(type: "TEXT", nullable: false),
                    localized_description = table.Column<string>(type: "TEXT", nullable: true),
                    count = table.Column<int>(type: "INTEGER", nullable: false),
                    rarity = table.Column<string>(type: "TEXT", nullable: true),
                    reference_id = table.Column<string>(type: "TEXT", nullable: true),
                    asset_path = table.Column<string>(type: "TEXT", nullable: true),
                    splash_path = table.Column<string>(type: "TEXT", nullable: true),
                    tile_path = table.Column<string>(type: "TEXT", nullable: true),
                    expires_at = table.Column<string>(type: "TEXT", nullable: true),
                    disenchant_value = table.Column<int>(type: "INTEGER", nullable: true),
                    upgrade_essence_value = table.Column<int>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_loot_items", x => new { x.account_id, x.loot_id });
                    table.ForeignKey(
                        name: "FK_loot_items_accounts_account_id",
                        column: x => x.account_id,
                        principalTable: "accounts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ranks",
                columns: table => new
                {
                    account_id = table.Column<string>(type: "TEXT", nullable: false),
                    queue_type = table.Column<string>(type: "TEXT", nullable: false),
                    tier = table.Column<string>(type: "TEXT", nullable: false),
                    division = table.Column<string>(type: "TEXT", nullable: false),
                    league_points = table.Column<int>(type: "INTEGER", nullable: false),
                    wins = table.Column<int>(type: "INTEGER", nullable: false),
                    losses = table.Column<int>(type: "INTEGER", nullable: false),
                    is_provisional = table.Column<int>(type: "INTEGER", nullable: false),
                    provisional_games_remaining = table.Column<int>(type: "INTEGER", nullable: true),
                    rated_tier = table.Column<string>(type: "TEXT", nullable: true),
                    rated_rating = table.Column<int>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ranks", x => new { x.account_id, x.queue_type });
                    table.ForeignKey(
                        name: "FK_ranks_accounts_account_id",
                        column: x => x.account_id,
                        principalTable: "accounts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "skins",
                columns: table => new
                {
                    account_id = table.Column<string>(type: "TEXT", nullable: false),
                    skin_id = table.Column<int>(type: "INTEGER", nullable: false),
                    champion_id = table.Column<int>(type: "INTEGER", nullable: false),
                    name = table.Column<string>(type: "TEXT", nullable: false),
                    splash_path = table.Column<string>(type: "TEXT", nullable: true),
                    tile_path = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_skins", x => new { x.account_id, x.skin_id });
                    table.ForeignKey(
                        name: "FK_skins_accounts_account_id",
                        column: x => x.account_id,
                        principalTable: "accounts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_accounts_login_region",
                table: "accounts",
                columns: new[] { "login_identifier", "region" });

            migrationBuilder.CreateIndex(
                name: "ix_accounts_puuid",
                table: "accounts",
                column: "puuid",
                unique: true,
                filter: "puuid IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_loot_account_category",
                table: "loot_items",
                columns: new[] { "account_id", "display_category" });

            migrationBuilder.CreateIndex(
                name: "ix_loot_account_name",
                table: "loot_items",
                columns: new[] { "account_id", "localized_name" });

            migrationBuilder.CreateIndex(
                name: "ix_loot_account_type",
                table: "loot_items",
                columns: new[] { "account_id", "type" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "account_sync_categories");

            migrationBuilder.DropTable(
                name: "champions");

            migrationBuilder.DropTable(
                name: "loot_items");

            migrationBuilder.DropTable(
                name: "ranks");

            migrationBuilder.DropTable(
                name: "skins");

            migrationBuilder.DropTable(
                name: "accounts");
        }
    }
}
