// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummonersVault.Infrastructure.Persistence;

#nullable disable

namespace SummonersVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VaultDbContext))]
    partial class VaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("BlueEssence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blue_essence");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<long?>("LastMatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_match_id");

                    b.Property<string>("LastMatchPlayedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_match_played_at");

                    b.Property<string>("LastSyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("LoginIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login_identifier");

                    b.Property<int>("MatchHistoryState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("match_history_state");

                    b.Property<string>("MatchHistorySyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("match_history_synced_at");

                    b.Property<string>("ModifiedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("password");

                    b.Property<byte[]>("ProfileIcon")
                        .HasColumnType("BLOB")
                        .HasColumnName("profile_icon");

                    b.Property<int?>("ProfileIconId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_icon_id");

                    b.Property<string>("Puuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("puuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("region");

                    b.Property<string>("RiotGameName")
                        .HasColumnType("TEXT")
                        .HasColumnName("riot_game_name");

                    b.Property<long?>("RiotPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("riot_points");

                    b.Property<string>("RiotTagLine")
                        .HasColumnType("TEXT")
                        .HasColumnName("riot_tag_line");

                    b.Property<int>("Roles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roles");

                    b.Property<long?>("SummonerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("summoner_id");

                    b.Property<int?>("SummonerLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("summoner_level");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_puuid")
                        .HasFilter("puuid IS NOT NULL");

                    b.HasIndex("LoginIdentifier", "Region")
                        .HasDatabaseName("ix_accounts_login_region");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.ChampionEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<int>("ChampionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("champion_id");

                    b.Property<string>("BaseSplashPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_splash_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SquarePortraitPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("square_portrait_path");

                    b.HasKey("AccountId", "ChampionId");

                    b.ToTable("champions", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.LootItemEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("LootId")
                        .HasColumnType("TEXT")
                        .HasColumnName("loot_id");

                    b.Property<string>("AssetPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_path");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<int?>("DisenchantValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disenchant_value");

                    b.Property<string>("DisplayCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_category");

                    b.Property<string>("ExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("localized_name");

                    b.Property<string>("LootName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("loot_name");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT")
                        .HasColumnName("rarity");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<string>("SplashPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("splash_path");

                    b.Property<string>("TilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("tile_path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int?>("UpgradeEssenceValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upgrade_essence_value");

                    b.HasKey("AccountId", "LootId");

                    b.HasIndex("AccountId", "DisplayCategory")
                        .HasDatabaseName("ix_loot_account_category");

                    b.HasIndex("AccountId", "LocalizedName")
                        .HasDatabaseName("ix_loot_account_name");

                    b.HasIndex("AccountId", "Type")
                        .HasDatabaseName("ix_loot_account_type");

                    b.ToTable("loot_items", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.RankEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("QueueType")
                        .HasColumnType("TEXT")
                        .HasColumnName("queue_type");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("division");

                    b.Property<int>("IsProvisional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_provisional");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("league_points");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("losses");

                    b.Property<int?>("ProvisionalGamesRemaining")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provisional_games_remaining");

                    b.Property<int?>("RatedRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rated_rating");

                    b.Property<string>("RatedTier")
                        .HasColumnType("TEXT")
                        .HasColumnName("rated_tier");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tier");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wins");

                    b.HasKey("AccountId", "QueueType");

                    b.ToTable("ranks", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.SkinEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skin_id");

                    b.Property<int>("ChampionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("champion_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SplashPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("splash_path");

                    b.Property<string>("TilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("tile_path");

                    b.HasKey("AccountId", "SkinId");

                    b.ToTable("skins", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.SyncCategoryEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<string>("LastAttemptAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastSuccessAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_success_at");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("AccountId", "Category");

                    b.ToTable("account_sync_categories", (string)null);
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.ChampionEntity", b =>
                {
                    b.HasOne("SummonersVault.Infrastructure.Persistence.AccountEntity", "Account")
                        .WithMany("Champions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.LootItemEntity", b =>
                {
                    b.HasOne("SummonersVault.Infrastructure.Persistence.AccountEntity", "Account")
                        .WithMany("LootItems")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.RankEntity", b =>
                {
                    b.HasOne("SummonersVault.Infrastructure.Persistence.AccountEntity", "Account")
                        .WithMany("Ranks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.SkinEntity", b =>
                {
                    b.HasOne("SummonersVault.Infrastructure.Persistence.AccountEntity", "Account")
                        .WithMany("Skins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.SyncCategoryEntity", b =>
                {
                    b.HasOne("SummonersVault.Infrastructure.Persistence.AccountEntity", "Account")
                        .WithMany("SyncCategories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SummonersVault.Infrastructure.Persistence.AccountEntity", b =>
                {
                    b.Navigation("Champions");

                    b.Navigation("LootItems");

                    b.Navigation("Ranks");

                    b.Navigation("Skins");

                    b.Navigation("SyncCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
