<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SummonersVault.Core\SummonersVault.Core.csproj" />
    <ProjectReference Include="..\SummonersVault.Infrastructure\SummonersVault.Infrastructure.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\blue-essence.png" />
    <Resource Include="Assets\rp.png" />
    <Resource Include="Assets\RankIcons\*.png" />
  </ItemGroup>
</Project>
